{% set version = "1.3.3" %}

package:
  name: fastpdb
  version: {{ version }}

source:
  url: https://github.com/biotite-dev/fastpdb/archive/v{{ version }}.tar.gz
  sha256: a0845e55606f321a9916fc890a4142ca48216224acb2a3cac7bfef9ef274d06e

build:
  number: 1
  script:
    - set PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1  # [win and py==314]
    - export PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1  # [unix and py==314]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=2.0                            # [build_platform != target_platform]
    - maturin                                # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
  host:
    - python
    - maturin >=1.4
    - numpy >=2.0
    - pip
  run:
    - python
    - numpy >=1.25
    - biotite >=1.0

test:
  source_files:
    - tests/
  requires:
    - pytest
  imports:
    - fastpdb
    - biotite
    - numpy
  commands:
    - pytest tests/ --ignore tests/test_version.py

about:
  home: https://github.com/biotite-dev/fastpdb
  summary: A high performance drop-in replacement for Biotite's PDBFile.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - padix-key
